import React, { useState } from "react";
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  Modal,
  ScrollView,
  Platform,
  KeyboardAvoidingView,
  Keyboard,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Alert } from "react-native";
import * as Linking from "expo-linking";
import * as WebBrowser from "expo-web-browser";
import DoctorProfileSetup from "./DoctorProfileSetup";
import ClinicSetup from "../settings/ClinicSetup";
import { CurrentUser } from "@smileguard/shared-types";
import { supabase } from "@smileguard/supabase-client";
import { useRouter } from "expo-router";

// CRITICAL: For iOS, handle the auth session completion
WebBrowser.maybeCompleteAuthSession();

export interface AuthModalProps {
  visible: boolean;
  onClose: () => void;
  onSuccess: (user: CurrentUser) => void;
}

export default function AuthModal({
  visible,
  onClose,
  onSuccess,
}: AuthModalProps) {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [tempUser, setTempUser] = useState<CurrentUser | null>(null);
  const inMultiStepFlowRef = React.useRef(false);

  // Reset state when modal re-opens (but not during multi-step flow)
  React.useEffect(() => {
    console.log("[AuthModal] Visibility changed to:", visible, "Step:", step, "InMultiStepFlow:", inMultiStepFlowRef.current);
    if (visible) {
      // Only reset to step 1 if not in the middle of multi-step auth flow
      if (!inMultiStepFlowRef.current) {
        console.log("[AuthModal] Resetting step to 1");
        setStep(1);
      } else {
        console.log("[AuthModal] In multi-step flow, NOT resetting step. Current step:", step);
      }
    } else {
      // When modal closes, reset the flow flag
      console.log("[AuthModal] Modal closed, resetting flow flag");
      inMultiStepFlowRef.current = false;
      Keyboard.dismiss();
    }
  }, [visible]);

  // Listen for OAuth auth state changes (SIGNED_IN after deep link redirect)
  React.useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      console.log("[AuthModal] Auth state changed:", event);
      if (event === "SIGNED_IN" && session?.user) {
        console.log("[AuthModal] SIGNED_IN detected for", session.user.email);
        setLoading(false);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const handleGoogleOAuth = async () => {
    try {
      setLoading(true);
      console.log("[GoogleOAuth] Starting Google OAuth...");

      const redirectUri = Linking.createURL("oauth-redirect");
      console.log("[AuthModal] Redirect URI:", redirectUri);
      
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: "google",
        options: {
          redirectTo: redirectUri,
          skipBrowserRedirect: true,
          queryParams: {
            prompt: "consent",
          },
        },
      });

      if (error) throw error;
      if (!data?.url) throw new Error("No OAuth URL generated by Supabase");

      console.log("[GoogleOAuth] Opening auth session...");
      const result = await WebBrowser.openAuthSessionAsync(data.url, redirectUri);
      console.log("[GoogleOAuth] Auth session result type:", result.type);

      if (result.type === "success") {
        console.log("[GoogleOAuth] Auth session succeeded, extracting tokens...");
        const extractParams = (urlString: string) => {
          const queryString = urlString.includes("#") ? urlString.split("#")[1] : urlString.includes("?") ? urlString.split("?")[1] : "";
          if (!queryString) return {} as Record<string, string>;
          return queryString.split("&").reduce((acc, current) => {
            const [key, value] = current.split("=");
            if (key && value) acc[key] = decodeURIComponent(value);
            return acc;
          }, {} as Record<string, string>);
        };

        const params = extractParams(result.url);
        console.log("[GoogleOAuth] Extracted params keys:", Object.keys(params));

        if (params.error_description) {
          throw new Error(`OAuth error: ${params.error_description}`);
        }

        if (params.access_token && params.refresh_token) {
          console.log("[GoogleOAuth] Setting session with tokens...");
          // CRITICAL: Mark that we're in multi-step flow NOW, before any async operations
          // This prevents root layout from resetting the step while we're processing OAuth
          inMultiStepFlowRef.current = true;
          
          const { error: sessionError } = await supabase.auth.setSession({
            access_token: params.access_token,
            refresh_token: params.refresh_token
          });
          
          if (sessionError) {
            console.error("[GoogleOAuth] Session error:", sessionError);
            throw sessionError;
          }

          console.log("[GoogleOAuth] Getting user...");
          const { data: { user }, error: userError } = await supabase.auth.getUser();
          if (userError) {
            console.error("[GoogleOAuth] User error:", userError);
            throw new Error("Failed to fetch user after OAuth");
          }
          if (!user) throw new Error("No user returned from getUser()");

          console.log("[GoogleOAuth] Got user:", user.email, "ID:", user.id);

          const { data: doctorProfile, error: profileError } = await supabase
            .from("doctors")
            .select("*")
            .eq("user_id", user.id)
            .single();

          console.log("[GoogleOAuth] Doctor profile query result:", {
            hasProfile: !!doctorProfile,
            errorCode: profileError?.code,
            errorMessage: profileError?.message
          });

          if (profileError && profileError.code !== "PGRST116") {
            console.error("[GoogleOAuth] Profile error:", profileError);
            throw profileError;
          }

          if (!doctorProfile) {
            console.log("[GoogleOAuth] No doctor profile found, advancing to step 2");
            // Multi-step flow ref already set at token extraction
            console.log("[GoogleOAuth] Setting step to 2, inMultiStepFlowRef:", inMultiStepFlowRef.current);
            setStep(2);
            setLoading(false);
            return;
          }

          console.log("[GoogleOAuth] Doctor profile exists, checking clinic...");
          const { data: clinicProfile, error: clinicError } = await supabase
            .from("clinics")
            .select("*")
            .eq("doctor_id", doctorProfile.id)
            .single();

          console.log("[GoogleOAuth] Clinic profile query result:", {
            hasClinic: !!clinicProfile,
            errorCode: clinicError?.code,
            errorMessage: clinicError?.message
          });

          if (clinicError && clinicError.code !== "PGRST116") {
            console.error("[GoogleOAuth] Clinic error:", clinicError);
            throw clinicError;
          }

          const userData: CurrentUser = {
            name: doctorProfile.doctor_name || user.email || "",
            email: user.email || "",
            role: "doctor",
          };

          if (!clinicProfile) {
            console.log("[GoogleOAuth] No clinic profile found, advancing to step 3");
            // Multi-step flow ref already set at token extraction
            setTempUser(userData);
            setStep(3);
            setLoading(false);
            return;
          }

          console.log("[GoogleOAuth] Both profiles exist, calling onSuccess");
          setLoading(false);
          onSuccess(userData);
        } else {
          console.error("[GoogleOAuth] No tokens in response. Available params:", Object.keys(params));
          throw new Error("No tokens returned from Google. Try again.");
        }
      } else if (result.type === "cancel") {
        console.log("[GoogleOAuth] User cancelled auth flow");
        setLoading(false);
      } else if (result.type === "dismiss") {
        console.log("[GoogleOAuth] Auth flow was dismissed");
        setLoading(false);
      } else {
        console.warn("[GoogleOAuth] Unexpected result type:", result.type);
        setLoading(false);
      }
    } catch (err) {
      let errorMessage = "Google sign-in failed.";
      if (err instanceof Error) {
        errorMessage = err.message;
        console.error("[GoogleOAuth] Full error:", err);
      }
      console.error("[GoogleOAuth] Sign-in error:", errorMessage);
      Alert.alert("Sign-in Error", errorMessage);
      setLoading(false);
    }
  };

  return (
    <Modal visible={visible} animationType="slide" onRequestClose={onClose}>
      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
      >
        <SafeAreaView style={styles.modalFull}>
          <ScrollView
            contentContainerStyle={styles.scrollContent}
            keyboardShouldPersistTaps="handled"
            showsVerticalScrollIndicator={false}
          >

            <View style={styles.stepContent}>
              {console.log("[AuthModal Render] Current step:", step, "Modal visible:", visible, "inMultiStepFlow:", inMultiStepFlowRef.current)}
              {step === 1 && (
                <View style={{ alignItems: "center" }}>
                  <Text style={styles.appName}>SmileGuard</Text>
                  <Text style={[styles.h2, { marginTop: 24, marginBottom: 8 }]}>Welcome!</Text>
                  
                  <Text style={[styles.subtitle, { marginBottom: 24 }]}>
                    Continue with Google to manage your patients.
                  </Text>

                  <TouchableOpacity
                    style={[styles.btn, styles.googleBtn]}
                    onPress={handleGoogleOAuth}
                    disabled={loading}
                  >
                    <Text style={styles.googleIcon}>G</Text>
                    <Text style={styles.googleBtnText}>
                      {loading ? "Signing in..." : "Continue with Google"}
                    </Text>
                  </TouchableOpacity>
                </View>
              )}

              {step === 2 && (
                <DoctorProfileSetup
                  onSuccess={(userData) => {
                    // Entering multi-step flow - don't reset step on modal visibility changes
                    inMultiStepFlowRef.current = true;
                    setTempUser(userData);
                    setStep(3);
                  }}
                  onCancel={() => {
                    inMultiStepFlowRef.current = false;
                    setStep(1);
                  }}
                />
              )}

              {step === 3 && (
                <ClinicSetup
                  onClose={() => {
                    // Flow is complete - clear the flag
                    inMultiStepFlowRef.current = false;
                    if (tempUser) {
                      onSuccess(tempUser);
                      // Navigate to dashboard after setup is complete
                      router.push("/(doctor)/dashboard");
                    }
                  }}
                />
              )}
            </View>
          </ScrollView>
        </SafeAreaView>
      </KeyboardAvoidingView>
    </Modal>
  );
}

const styles = StyleSheet.create({
  modalFull: { flex: 1, padding: 30 },
  scrollContent: { flexGrow: 1, justifyContent: "center" },
  stepContent: {
    marginTop: 20,
    borderColor: "#2bf1ff7d",
    borderWidth: 1,
    borderRadius: 45,
    padding: 24,
    backgroundColor: "#fff",
  },
  appName: { fontSize: 28, fontWeight: "700", color: "#0b7fab" },
  h2: { fontSize: 24, fontWeight: "800", color: "#0f172a", textAlign: "center" },
  subtitle: { fontSize: 14, color: "#6b7280", textAlign: "center", lineHeight: 20 },
  btn: { paddingVertical: 14, paddingHorizontal: 28, borderRadius: 10, alignItems: "center", width: "100%" },
  googleBtn: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#d1d5db", flexDirection: "row", justifyContent: "center" },
  googleIcon: { fontSize: 18, fontWeight: "700", color: "#374151", marginRight: 8 },
  googleBtnText: { color: "#374151", fontWeight: "600", fontSize: 15 },
  closeBtn: { padding: 8 },
  closeBtnText: { fontSize: 20, color: "#6b7280" },
});

